name: pytest

on:
  push:
    branches: '*'
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Anaconda Using Python ${{ matrix.python-version }}
      uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: microdf
        environment-file: C:/Users/prana/anaconda3/envs/my-rdkit-env/environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Build
      shell: bash
      run: |
        pip install -e .
    - name: Run pytest
      shell: bash
      run: | 
        pytest -v tests
        
