name: pytest

on:
  push:
    branches: '*'
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: actions/cache@v3
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/environment.yml') }}
        restore-keys: | 
          ${{ runner.os }}-pip-
    - name: Export and Install Conda environment
      run: |
        conda activate <name-of-your-env>
        conda env export --no-builds | grep -v "^prefix: " > /tmp/environment.yml
        conda env create -f /tmp/environment.yml
        conda activate <name-of-your-env>
    - name: Run pytest
      run: | 
        pytest
    - name: Clean up temporary file
      run: |
        rm /tmp/environment.yml
